# version: '3'

# services:
#   go-service:
#     build:
#       context: ./go-service
#     ports:
#       - "8080:8080"

#   nestjs-service:
#     build:
#       context: ./nestjs-service
#     ports:
#       - "3000:3000"
#     depends_on:
#       - go-service

#########################################

# version: '3'

# services:
#   go-service:
#     build:
#       context: ./go-service
#     ports:
#       - "8080:8080"

#   nestjs-service:
#     build:
#       context: ./nestjs-service
#     ports:
#       - "3000:3000"
#     depends_on:
#       - go-service
#       - mongo

#   mongo:
#     image: mongo:latest
#     ports:
#       - "27017:27017"

#########################################

# version: '3.8'

# services:
#   go-service:
#     build:
#       context: ./go-service
#     ports:
#       - "8080:8080"

#   nestjs-service:
#     build:
#       context: ./nestjs-service
#     ports:
#       - "3000:3000"
#     depends_on:
#       - go-service
#       - mongo
#     environment:
#       - MONGO_URI=mongodb://mongo:27017/mydb


#   mongo:
#     image: mongo:latest
#     ports:
#       - "27017:27017"
#     volumes:
#       - mongo-data:/data/db

# volumes:
#   mongo-data:


#########################################

# version: '3.8'

# services:
#   go-service:
#     build:
#       context: ./go-service
#     ports:
#       - "8080:8080"
#     environment:
#       - TZ=America/Los_Angeles  # Set your desired time zone

#   nestjs-service:
#     build:
#       context: ./nestjs-service
#     ports:
#       - "3000:3000"
#     depends_on:
#       - go-service
#       - mongo
#     environment:
#       - MONGO_URI=mongodb://mongo:27017/mydb
#       - TZ=America/Los_Angeles  # Set your desired time zone

#   mongo:
#     image: mongo:latest
#     ports:
#       - "27017:27017"
#     volumes:
#       - mongo-data:/data/db
#     environment:
#       - TZ=America/Los_Angeles  # Set your desired time zone

# volumes:
#   mongo-data:

#########################################


version: '3.8'

services:
  go-service:
    build:
      context: ./go-service
    ports:
      - "8080:8080"
    environment:
      - TZ=America/Los_Angeles  # Set your desired time zone
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  nestjs-service:
    build:
      context: ./nestjs-service
    volumes:
      - ./nestjs-service:/usr/src/app      
    ports:
      - "3000:3000"
    depends_on:
      - go-service
      - mongo
    environment:
      - MONGO_URI=mongodb://mongo:27017/mydb
      - TZ=America/Los_Angeles  # Set your desired time zone
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    environment:
      - TZ=America/Los_Angeles  # Set your desired time zone
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

volumes:
  mongo-data:
